### ISSUE TITLE
Trouble unboxing package

### ISSUE THREAD

**Issue by gustavoparedes1978** [Quintor/angular-truffle-box#20]
Hi, I'm getting the following log while unboxing:

gustavoparedes1978@gustavoparedes1978-HP-Pavilion-g4-Notebook-PC:~$ sudo npm install -g @angular/cli
[sudo] password for gustavoparedes1978: 
/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng

> node-sass@4.7.2 install /usr/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux-x64-59 : { Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:905:18)
    at sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /usr/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.2.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.2.0
gyp verb command install [ '9.2.0' ]
gyp verb install input version string "9.2.0"
gyp verb install installing version: 9.2.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.2.0
gyp verb build dir attempting to create "build" dir: /usr/lib/node_modules/@angular/cli/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/build'
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/@angular/cli/node_modules/node-sass
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules/@angular/cli/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @angular/cli@1.5.5
added 160 packages and updated 1 package in 92.692s

**Comment by pimotte** [comment]
Looks like you're getting a permission error. I highly recommend not installing all the dependencies globally. Try using `npm install` instead (i.e. install the dependencies locally.) It's only recommended to install the commands you want to use everywhere (i.e. truffle, angular-cli and testrpc) globally.

**Comment by gustavoparedes1978** [comment]
Thanks you, I will try it later and let you know.

**Comment by gustavoparedes1978** [comment]
No, I keep getting the same messages all over again even though i'm not installing it globally. So, I will leave it just as it is.

**Comment by pimotte** [comment]
The log really looks like something weird is up with the permissions in your node install. Can you build other projects without issues?

**Comment by gustavoparedes1978** [comment]
Yes, I can build other projects, even bigger ones, such as node.js or npm, or truffle, or docker, or any other truffle box, so I think it has something to do with the building scripts, and I think I'm getting the idea from here: /usr/lib/node_modules//node_modules/node-sass/build, Do you see that double slash from node_modules, that's a mistake from the script itself, you need to correct it

**Comment by pimotte** [comment]
I think the issue rather lies in the /usr/lib/node_modules. Can you post the stacktrace you get when you run `npm install`? (without sudo and without -g)

**Comment by pimotte** [comment]
If this issue still persists when running without sudo and -g, feel free to reopen this.
