### ISSUE TITLE
ERROR TypeError: web3_1.default is not a constructor

### ISSUE THREAD

**Issue by agrofcsik** [Quintor/angular-truffle-box#22]
On: 
this.web3 = new Web3(window.web3.currentProvider); 
in web3.service.ts

I'm getting the following:
ERROR TypeError: web3_1.default is not a constructor

**Comment by agrofcsik** [comment]
This seemed to solve my issue for now:
https://github.com/ethereum/web3.js/issues/1155

**Comment by Ritin** [comment]
@agrofcsik the solution at [ethereum/web3.js#1155](url)
did not work for me
`import Web3 from 'web3';`
gives the above mentioned (TypeError: web3_1.default is not a constructor)
`import * as Web3 from 'web3';`
webpack compile **Fails**
```
+-- truffle-contract@3.0.2
| +-- truffle-blockchain-utils@0.0.3
| | `-- web3@0.20.4 
| `-- web3@0.20.4 
`-- web3@1.0.0-beta.29 
```
@angular/cli@1.6.6
@angular/compiler-cli@5.2.2

However downgrading **works** 
`import Web3 from 'web3';`
```
+-- truffle-contract@3.0.1
| +-- truffle-blockchain-utils@0.0.3
| | `-- web3@0.20.2 
| `-- web3@0.20.2 
`-- web3@1.0.0-beta.26 
```
@angular/compiler-cli@5.1.1
@angular/cli@1.6.1

**Comment by agrofcsik** [comment]
I ended up giving up and going with: angular4-truffle-starter-dapp which seems to work better.

**Comment by kmturley** [comment]
when changing from:
`import Web3 from 'web3';`

to:
`import * as Web3 from 'web3';`

I get a different error afterwards:
> truffle_contract_1.default is not a function

Which seems to be fixed by changing the line:
`import {default as contract} from 'truffle-contract';`

to:
`const contract = require('truffle-contract');`

**Comment by sergeym610** [comment]
ERROR TypeError: web3_1.default is not a constructor
This problem was made me crazy a few days.
I used "npm install web3 --save" command and import Web3 from 'web3';
So, the error occurred!
In my experience, I removed  "import Web3 from 'web3';" and added new lines like 
"declare let Web3: any;
 declare let web3;"

It works correctly for me.
I hope that this is correct resolve.
Thanks
