### ISSUE TITLE
TypeChain

### ISSUE THREAD

**Issue by meherett** [Quintor/angular-truffle-box#23]
How can we use TypeChain in angular 2+?

**Comment by pimotte** [comment]
Generating the code and refactoring the existing code starting around here: https://github.com/Quintor/angular-truffle-box/blob/master/src/app/meta/meta-sender/meta-sender.component.ts#L31 should be doable. The type of the MetaCoin would then be any. I also tend to do the calls with .sendTransaction or .call explicitly, which I don't think the TypeChain library supports?

I'd be happy to accept a PR that does this cleanly. If I were to start working on it myself, I'll post it here.

**Comment by meherett** [comment]
OK @pimotte,

Please!

I didn't understand meta-sender.component.ts, If i would like to give you sample smart contract so that give me an example of angular-truffle.


"pragma solidity ^0.4.8;
contract Storage {
  uint256 storedData;
function set(uint256 data) {
    storedData = data;
  }
function get() constant returns (uint256) {
    return storedData;
  }
}"

Please! @pimotte

**Comment by pimotte** [comment]
https://github.com/Quintor/angular-truffle-box/blob/master/src/app/meta/meta-sender/meta-sender.component.ts#L63 and https://github.com/Quintor/angular-truffle-box/blob/master/src/app/meta/meta-sender/meta-sender.component.ts#L81 are the lines where the contract interaction happens. If you want to do that with TypeChain, you should end up with the needed object around those lines.

In general, using TypeChain with angular shouldn't be that different from using other libraries from angular, except maybe that the code is generated.

**Comment by meherett** [comment]
I am ok in typechain but i need this please

"pragma solidity ^0.4.8;
contract Storage {
uint256 storedData;
function set(uint256 data) {
storedData = data;
}
function get() constant returns (uint256) {
return storedData;
}
}"

**Comment by pimotte** [comment]
If you want to implement an application that uses that contract, I recommend forking this repo and throwing away meta-sender.component.ts, and implement a new component that interacts with it.

This Truffle box already has the MetaCoin contract as an example, so an additional contract is not needed.

**Comment by meherett** [comment]
Constructor: [object Object]
meta-sender.component.ts:28 OnInit: [object Object]
meta-sender.component.ts:29 MetaSenderComponent {web3Service: Web3Service, model: Object, status: ""}model: Objectstatus: ""web3Service: Web3Service__proto__: Object
core.js:3675 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
core.js:1440 ERROR TypeError: web3_1.default is not a constructor
    at Web3Service.bootstrapWeb3 (web3.service.ts:26)
    at eval (web3.service.ts:18)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4724)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1517)
    at globalZoneAwareCallback (zone.js:1543)
defaultErrorLogger @ core.js:1440
ErrorHandler.handleError @ core.js:1501
next @ core.js:5491
schedulerFn @ core.js:4319
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4299
(anonymous) @ core.js:4755
ZoneDelegate.invoke @ zone.js:388
Zone.run @ zone.js:138
NgZone.runOutsideAngular @ core.js:4681
onHandleError @ core.js:4755
ZoneDelegate.handleError @ zone.js:392
Zone.runTask @ zone.js:191
ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1517
globalZoneAwareCallback @ zone.js:1543

**Comment by pimotte** [comment]
Did you get any errors when installing dependencies?

**Comment by meherett** [comment]
no i didn't get

**Comment by meherett** [comment]
no i didn't get

**Comment by meherett** [comment]
Error
https://github.com/Quintor/angular-truffle-box/blob/master/src/app/util/web3.service.ts#26

**Comment by pimotte** [comment]
If any of these issues still exist, feel free to create a new issue with a description how to reproduce them.
