### ISSUE TITLE
Event example

### ISSUE THREAD

**Issue by salvdev** [Quintor/angular-truffle-box#28]
Can we get an example of receiving an Event when updating the state of a contract?

For example the sendCoin() function in the MetaCoin.sol file emits a Transfer event when successfully evoked. How does one console.log this Event when sent back to the client?

**Comment by pimotte** [comment]
Yep, this is something that would be a useful addition (see #10). 

If I start working on this, I'll let you know. If someone else wants to pick it up, let me know, and I'll be happy to review and merge it.

**Comment by pimotte** [comment]
Closing this as a duplicate of #10
