### ISSUE TITLE
Use Ganache instead of TestRPC

### ISSUE THREAD

**Issue by GuillaumeCz** [Quintor/angular-truffle-box#29]
Ganache is the new TestRPC. It could be greate to update the readMe and the packages with this new name

**Comment by pimotte** [comment]
Technically ganache-cli, right? In any case, I'm happy to accept a PR for this.

**Comment by GuillaumeCz** [comment]
Yes it is ganache-cli ;) It's very similar to testRpc, I think only the name was changed

**Comment by pimotte** [comment]
The cave-at here is that the ci broke for some reason (I think having to do with (headless) chrome https://travis-ci.org/Quintor/angular-truffle-box/builds/317636274 ) 

The easiest way to verify that ganache-cli doesn't break anything is to fix the integration test and then update the versions.

**Comment by pimotte** [comment]
I fixed the ci issue in #30
