### ISSUE TITLE
When try to unbox, can't find Python executable even it is already installed

### ISSUE THREAD

**Issue by Muhammad-Altabba** [Quintor/angular-truffle-box#32]
Getting an error Can't find Python executable "C:\Program Files (x86)\Python36-32\python.exe". But the file is already exist at the mentioned path.

Command:
`truffle unbox Quintor/angular-truffle-box`

Output:
```
Downloading...
Unpacking...
Setting up...
Error: Command failed: npm install
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Program Files (x86)\Python36-32\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Dev\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Dev\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Dev\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:112:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dev\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\BlockChain\angular4\node_modules\scrypt
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev\AppData\Roaming\npm-cache\_logs\2018-03-24T21_38_38_927Z-debug.log

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Versions:
npm version: 5.7.1
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)] on win32
Windows 10
Truffle v4.1.3 (core: 4.1.3)
Solidity v0.4.19 (solc-js)

**Comment by pimotte** [comment]
I've only tested this with Python version 2.7, so try that, rather than 3.x. Also, as the output suggests "you can set the PYTHON env variable." to point to the place where you've installed Python.

**Comment by Muhammad-Altabba** [comment]
I already have the PYTHON  evn variable set correctly. And I not not like the idea of down grading to version 2.7 but I will try it. Thanks,

**Comment by pimotte** [comment]
Feel free to reopen this if the issue persists after using python 2. This dependency is so far down that I can't really support Python 3.

**Comment by wowripper** [comment]
npm install -g windows-build-tools
https://trufflesuite.com/boxes/angular-truffle-box/index.html
Prerequisites¶
In order to run the Truffle box, you will need Node.js (tested with version 10.x.y). This will include npm, needed to install dependencies. In order install these dependencies, you will also need Python (version 2.7.x) and git. You will also need the MetaMask plugin for Chrome.
