### ISSUE TITLE
Error: Contract has not been deployed to detected network (network/artifact mismatch)

### ISSUE THREAD

**Issue by Muhammad-Altabba** [Quintor/angular-truffle-box#35]
I am facing the issue while using the latest version of this truffle box.

However, it is not preset if I run `ng serve -prod`.

`node -v`
> v8.11.1

`truffle version`
> Truffle v4.1.5 (core: 4.1.5)
> Solidity v0.4.21 (solc-js)

`npm version`
> { 'angular-truffle-box': '0.0.0',
>   npm: '5.8.0',
>   ares: '1.10.1-DEV',
>   cldr: '32.0',
>   http_parser: '2.8.0',
>   icu: '60.1',
>   modules: '57',
>   nghttp2: '1.25.0',
>   node: '8.11.1',
>   openssl: '1.0.2o',
>   tz: '2017c',
>   unicode: '10.0',
>   uv: '1.19.1',
>   v8: '6.2.414.50',
>   zlib: '1.2.11' }

`ng version`

> Angular CLI: 1.7.3
> Node: 8.11.1
> OS: linux x64
> Angular: 5.2.9
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, platform-browser, platform-browser-dynamic
> ... platform-server, router
> 
> @'angular/cli: 1.7.3
> @'angular/language-service: 4.4.6
> @'angular-devkit/build-optimizer: 0.3.2
> @'angular-devkit/core: 0.4.8
> @'angular-devkit/schematics: 0.3.2
> @'ngtools/json-schema: 1.2.0
> @'ngtools/webpack: 1.10.2
> @'schematics/angular: 0.3.2
> @'schematics/package-update: 0.3.2
> typescript: 2.4.2
> webpack: 3.11.0

JavaScript libraries' versions as mentioned at current package.json:

> ```
> "@angular/animations": "^5.2.9",
> "@angular/common": "^5.2.9",
> "@angular/compiler": "^5.2.9",
> "@angular/core": "^5.2.9",
> "@angular/forms": "^5.2.9",
> "@angular/http": "^5.2.9",
> "@angular/platform-browser": "^5.2.9",
> "@angular/platform-browser-dynamic": "^5.2.9",
> "@angular/platform-server": "^5.2.9",
> "@angular/router": "^5.2.9",
> "core-js": "^2.5.4",
> "rxjs": "^5.5.8",
> "web3": "^1.0.0-beta.34",
> "zone.js": "^0.8.23"
> ```

**Comment by pimotte** [comment]
Did you run `truffle migrate` after starting testrpc?

**Comment by Muhammad-Altabba** [comment]
Your update https://github.com/Quintor/angular-truffle-box/pull/36 resolved the issue. Thanks,
