### ISSUE TITLE
Upgrade to angular 6.0

### ISSUE THREAD

**Issue by pimotte** [Quintor/angular-truffle-box#38]
Since it's available: [Release Notes](https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4)

Wins for us would be the webpack upgrade maybe solving some of the import issues and the versions for the cli being matched to the angular versions

**Comment by MajdTL1** [comment]
i'm still not able to use web3 1.0 with Angular 6, an upgrade to the box would be free helpfull

**Comment by pimotte** [comment]
Closed with #41
