### ISSUE TITLE
Having trouble unboxing this box

### ISSUE THREAD

**Issue by breckinridge22** [Quintor/angular-truffle-box#40]
When I try to unbox this I receive this error log: 
1 error generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack at ChildProcess.emit (events.js:182:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/10.4.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/BreckStodghill/workspace/truffleAngular/node_modules/sha3
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pimotte** [comment]
I see you're using node v10.4.1. Does the same issue exist for node 8.9.x?

**Comment by pimotte** [comment]
I've tested with node 10. If this issue still persists, feel free to reopen this with some more details (preferably what's above in the stacktrace you copied).
