### ISSUE TITLE
accounts balance happend but dont refresh on ganache or metamask

### ISSUE THREAD

**Issue by belenmartinsoltel** [Quintor/angular-truffle-box#45]
Hello i have unboxing Quintor on this enviroment:

Windows 10
Truffle v5.0.0 (core: 5.0.0)
Solidity v0.5.0 (solc-js)
Node v10.14.2
Angular :  (7.1.0)
Visual Code Studio like IDE
Ganache 
I have unboxing, compile and migration well. 
I can see the web app but the first thing that I see extrange is in real balance in ganache or metamask first acount have 9999.98 ETH and in web i see You have 10000 META

The address of the first account is the same that I have in ganache or metamask 0xF6E59Ed94346E1e2e7e232A92b640761e4851E83. If i selected other account in metamask this address change.  So I try to send 100 to  my second address ( I have 5) 0xA49E8fDD3033Ed17cf732dbB94B0E15eC9d3339A and when I send MetaCoin appears this:
![image](https://user-images.githubusercontent.com/46002265/50591733-4dcf7880-0e91-11e9-8373-6a6a70abde98.png)
But the receiver address is always this: 0xBF5FaBf41260908c7A5505D0204a79da3a36DF77
I push on Confirm  say transaction done , on app i see 9990 but on ganache or metamask nothing have been changed.

**Comment by belenmartinsoltel** [comment]
I have reset the migration with truffle migration --reset 
And now the receiver address is 0xb178A84028d0931300AC5c66a53eEd54f69dd7d0 
In ganache ui i see the transaction but dont send the metacoin:
![image](https://user-images.githubusercontent.com/46002265/50592767-d18b6400-0e95-11e9-85d1-b1509c21c704.png)

![image](https://user-images.githubusercontent.com/46002265/50592779-dd772600-0e95-11e9-970a-6645f6c57941.png)

**Comment by pimotte** [comment]
I've updated the codebase to function with truffle v5, does this issue still exist now?

**Comment by belenmartinsoltel** [comment]
Now  I have this error when i send meta (error on metamask)

ALERT: [ethjs-rpc] rpc error with payload {"id":7273423220441,"jsonrpc":"2.0","params":["0xf8aa1f847735940082f91d94bf5fabf41260908c7a5505d0204a79da3a36df7780b84490b98a11000000000000000000000000a49e8fdd3033ed17cf732dbb94b0e15ec9d3339a0000000000000000000000000000000000000000000000000000000000000064822d45a00d11ae1f7b4e1800679cd321b7e3537e8b31f7a668c52e7ad7acb5f2ef33fbb1a07aa5fbd972351e51101d49d29600e2f2424461ea055076042ee6e9c40f990a6b"],"method":"eth_sendRawTransaction"} Error: the tx doesn't have the correct nonce. account has nonce of: 11 tx has nonce of: 31
RECHAZAR

**Comment by pimotte** [comment]
This is a common issue when restarting ganache. You can reset metamask by going to Settings -> reset account

**Comment by pimotte** [comment]
I'm assuming this is resolved, if you have more issues, feel free to reopen this issue or open a new one:)
